//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by jung on 4/12/24.
//

import ProjectDescription

let workspace = Workspace(
	name: "Photi",
	projects: [
		"Projects/App",
		"Projects/Core",
		"Projects/Data",
		"Projects/DesignSystem",
		"Projects/Domain",
		"Projects/Presentation"
	],
	schemes: [
		Scheme(
			name: "Photi-DEV",
			buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Photi-DEV")]),

			runAction: .runAction(configuration: .debug),
			archiveAction: .archiveAction(configuration: .debug),
			profileAction: .profileAction(configuration: .debug),
			analyzeAction: .analyzeAction(configuration: .debug)
		),
		Scheme(
			name: "Photi-PROD",
			buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Photi-PROD")]),
			runAction: .runAction(configuration: .release),
			archiveAction: .archiveAction(configuration: .release),
			profileAction: .profileAction(configuration: .release),
			analyzeAction: .analyzeAction(configuration: .release)
		)
	],
	generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
